### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Spurlex** [Kratous/Issues#12]
[18:52:51] [Server thread/ERROR]: Could not pass event PlayerMoveEvent to GameCore v1.9 DEV
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.PlayerConnection.a(PlayerConnection.java:578) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.PacketPlayInFlying.a(SourceFile:126) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
	at net.minecraft.server.v1_9_R1.SystemUtils.a(SourceFile:45) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:721) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot-1.9.jar:git-Spigot-3af4605-ed8cef0]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
Caused by: java.lang.NullPointerException

**Comment by JayNZ** [comment]
Unable to reproduce.
